name: on pull request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
      - edited
      - reopened
    branches:
      - main

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  # Run the unit tests on every PR, even from external repos
  unit_tests:
    uses: ./.github/workflows/tox.yaml
